Enhancement/sel to bracket
facelessuser/BracketHighlighter pull request #566
Opened 2020-08-25 17:13 UTC by MinorProphet

This change adds an additional argument to the Select Bracket plugin called 'extend' that allows a user to extend their current selection while jumping to a bracket via the SelectBracket::select_left() and SelectBracket::select_right() methods.

For instance, if your cursor was in the middle of some text between 2 brackets and the user invoked the Select Bracket plugin with arguments "select"="right" and "extend"=true, the right half of the text would be selected up, but not including, the right bracket.

This new behavior will mimic the current behavior of jumping to the parent brackets if continually calling the Select Bracket plugin with the same arguments.

Continuing with the previous example, if the Select Bracket plugin was called again with the same arguments, now the right half of the text would be selecting up to, and including the right bracket.  And if called again, all the text to the right of the cursor up to, but not including, the parent bracket would be selected.

This behavior attempts to fulfill the expectation a user might have if shift was held while jumping to the left or right bracket.

2020-08-26 00:06 UTC, facelessuser commented
Sounds interesting. I'll take a look sometime this week. I'll let you know if there are any issues.

Thanks for the pull!

2020-09-28 02:26 UTC, facelessuser commented
Sorry, it has taken me a bit to get back to this. I will be taking a closer look this week.

2020-10-11 22:00 UTC, facelessuser requested changes

2020-10-11 22:44 UTC, MinorProphet commented on bh_modules/bracketselect.py
> +    def run(self, edit, name, select='', extend=False, tags=None, always_include_brackets=False, alternate=False):
Will fix/have fixed.

2020-10-12 03:26 UTC, facelessuser commented
@gir-bot lgtm

2020-10-12 03:27 UTC, facelessuser approved these changes

2020-10-12 03:27 UTC, merged